"""Write the question doc every lane asks from, questions/spx_questions.json, from the final question set.

    python3 spec/write_question_docs.py                          # from spec/question_set.json
    python3 spec/write_question_docs.py --set ~/edited-set.json  # an edited set (copy it over spec/question_set.json to keep it)
    python3 spec/write_question_docs.py --check                  # say whether the doc on disk and the set's counts are what the set makes

The set is the one source of the questions: an edit is made there and the doc regenerated, never edited by
hand. On the way each question is keyed by its id inside its group, and:

* JEV's ``criteria`` are the options' own words: a choice's and a yes/no's by option name, a score's as a
  list in level order. The set's ``criteria``, the rule code judges each option by, ride beside them as
  ``code_criteria``; the option names are kept in order as ``options``.
* Every field the code reads is kept as the set wrote it: status, dark_reason, type, serves, lanes, the per-lane
  schedule and horizon, cadence (for people), sleep_when, code_answer, ref_side, shadow_proof, and why;
  merged_id (the id a judgment question had in the merged set); and ``ask``, the question in one short plain sentence that the sums read an answer after (hour.py)
  and the phone shows, never sent to JEV with the question itself.
  The review record (evidence, origin, sources, labels_needed) stays in the set; ``labels`` names what
  the question reads.

The set's own ``counts`` block is worked out from what the set holds (set_counts) and written back into the set
with the doc, so a tally can never lag the questions, labels and constants it counts.

The doc is written only when the set's constants are cuts.py's to the number and the result loads for every
lane (every brace names a constant, every schedule reads, no group over the cap); otherwise nothing is
written and the reason is printed.
"""
from __future__ import annotations

import argparse
import json
import sys
import tempfile
from collections import Counter
from pathlib import Path

SKILL = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(SKILL))

from spx_jev.ask import load_questions  # noqa: E402
from spx_jev.cuts import QUESTION_CONSTANTS  # noqa: E402
from spx_jev.lane import LANES, QUESTIONS  # noqa: E402

QUESTION_SET = SKILL / "spec" / "question_set.json"
KEPT = ("status", "type", "serves", "lanes", "schedule", "horizon", "cadence", "sleep_when", "code_answer", "ref_side",
        "shadow_proof", "ask", "instructions", "dark_reason", "merged_id")


def jev_criteria(q: dict) -> dict | list:
    """The words JEV chooses between: the options' descriptions, by name, or in level order for a score."""
    if q["type"] == "score":
        return [o["description"] for o in q["options"]]
    return {o["name"]: o["description"] for o in q["options"]}


def doc_question(q: dict) -> dict:
    out = {k: q[k] for k in KEPT if k in q}
    out["options"] = [o["name"] for o in q["options"]]
    out["criteria"] = jev_criteria(q)
    out["code_criteria"] = q["criteria"]
    out["labels"] = [lab["name"] for lab in q["labels_needed"]]
    out["why"] = q["why"]
    return out


def question_doc(qset: dict, source: str) -> dict:
    return {
        "name": "SPX JEV questions, every lane",
        "generated_from": {"file": source, "set": qset["name"], "version": qset["version"], "date": qset["date"]},
        "status": "generated by spec/write_question_docs.py: edit the set and regenerate, never this file",
        "owner_rule": qset["owner_rule"],
        "how_to_use": ("Step 2 of the pipeline. Each lane asks the questions whose lanes name it (the live lane "
                       "thirty_minute, the opening lane opening_five_minute, the pre-market lane premarket), at the reads its schedule names: live ones "
                       "count in the sums, shadow ones are asked and logged but never graded or weighted, dark ones are never asked. "
                       "A question with sleep_when is asked only when its label family says it is awake. Every threshold "
                       "is a name in braces filled from spx_jev/cuts.py."),
        "groups": [{"id": g["id"], "lane": g["lane"], "purpose": g["purpose"], "reads": g["reads"],
                    "questions": {q["id"]: doc_question(q) for q in g["questions"]}} for g in qset["groups"]],
    }


def set_counts(qset: dict) -> dict:
    """The set's tallies of its questions (by status, lane, group and what they serve), labels and constants. A
    lane's question and group counts are its live ones; the market questions are every live one."""
    questions = [q for g in qset["groups"] for q in g["questions"]]
    live = [q for q in questions if q["status"] == "live"]

    def on(lane: str) -> list[dict]:
        return [q for q in live if lane in q.get("lanes", [])]

    def live_groups(lane: str) -> int:
        return sum(1 for g in qset["groups"] if g["lane"] == lane and any(q["status"] == "live" for q in g["questions"]))

    def tally(items) -> dict:
        return dict(Counter(items).most_common())

    return {
        "questions": len(questions),
        "by_status": tally(q["status"] for q in questions),
        "live_market_questions": len(live),
        "premarket_questions": len([q for q in questions if "premarket" in q.get("lanes", [])]),
        "opening_lane_questions": len(on("opening_five_minute")),
        "thirty_minute_lane_questions": len(on("thirty_minute")),
        "groups_thirty_minute": live_groups("thirty_minute"),
        "groups_opening": live_groups("opening_five_minute"),
        "groups_premarket": live_groups("premarket"),
        "by_serves": tally(q["serves"] for q in questions),
        "by_serves_live": tally(q["serves"] for q in live),
        "by_group": {g["id"]: tally(q["status"] for q in g["questions"]) for g in qset["groups"]},
        "labels": len(qset["labels"]),
        "constants": len(qset["constants"]),
        "label_availability": tally(lab["availability"] for lab in qset["labels"]),
    }


def constant_differences(qset: dict) -> list[str]:
    """Every set constant cuts.py lacks or holds at another number."""
    out = []
    for name, entry in qset["constants"].items():
        if name not in QUESTION_CONSTANTS:
            out.append(f"{name}: in the set ({entry['value']}), not in cuts.py")
        elif QUESTION_CONSTANTS[name] != entry["value"] or type(QUESTION_CONSTANTS[name]) is not type(entry["value"]):
            out.append(f"{name}: the set says {entry['value']!r}, cuts.py {QUESTION_CONSTANTS[name]!r}")
    return out


def rendered(qset: dict, source: str) -> str:
    return json.dumps(question_doc(qset, source), ensure_ascii=False, indent=1) + "\n"


def loads_for_every_lane(text: str) -> None:
    """Raise if the doc does not load for a lane: an unknown constant, a schedule the code cannot read, a
    group over the cap."""
    with tempfile.TemporaryDirectory() as tmp:
        path = Path(tmp) / QUESTIONS.name
        path.write_text(text, encoding="utf-8")
        for lane in LANES.values():
            load_questions(path, lane.key)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Write questions/spx_questions.json from the final question set.")
    ap.add_argument("--set", default=str(QUESTION_SET), help="the question set, default spec/question_set.json")
    ap.add_argument("--out", default=str(QUESTIONS))
    ap.add_argument("--check", action="store_true", help="write nothing; exit 1 when the doc on disk differs from the set's")
    args = ap.parse_args(argv)
    qset = json.loads(Path(args.set).read_text(encoding="utf-8"))
    diffs = constant_differences(qset)
    if diffs:
        print("the set's constants and cuts.py disagree; change cuts.py first:\n  " + "\n  ".join(diffs), file=sys.stderr)
        return 1
    source = Path(args.set).resolve()
    text = rendered(qset, str(source.relative_to(SKILL)) if source.is_relative_to(SKILL) else source.name)
    try:
        loads_for_every_lane(text)
    except ValueError as e:
        print(f"the doc would not load, nothing written: {e}", file=sys.stderr)
        return 1
    out = Path(args.out)
    counts = set_counts(qset)
    if args.check:
        same = out.is_file() and out.read_text(encoding="utf-8") == text
        print(f"{out} {'matches' if same else 'differs from'} {args.set}")
        if qset["counts"] != counts:
            print(f"{args.set}'s counts are not what it holds; run without --check to rewrite them")
        return 0 if same and qset["counts"] == counts else 1
    if qset["counts"] != counts:
        qset["counts"] = counts
        Path(args.set).write_text(json.dumps(qset, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
        print(f"rewrote {args.set}'s counts")
    out.write_text(text, encoding="utf-8")
    n = sum(len(g["questions"]) for g in qset["groups"])
    print(f"wrote {out}: {n} questions in {len(qset['groups'])} groups from {args.set}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
